---
description: '자세히 알아보기: System.identitymodel. IdentityModelAsyncCallbackThrewException'
title: System.IdentityModel.IdentityModelAsyncCallbackThrewException
ms.date: 03/30/2017
ms.assetid: e4fc924f-3b9e-44f5-97e4-b3a4bb855d89
ms.openlocfilehash: 304cf448b71c6a0aa901a09273b81b686020d0f2
ms.sourcegitcommit: ddf7edb67715a5b9a45e3dd44536dabc153c1de0
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 02/06/2021
ms.locfileid: "99635289"
---
# <a name="systemidentitymodelidentitymodelasynccallbackthrewexception"></a><span data-ttu-id="a69dd-103">System.IdentityModel.IdentityModelAsyncCallbackThrewException</span><span class="sxs-lookup"><span data-stu-id="a69dd-103">System.IdentityModel.IdentityModelAsyncCallbackThrewException</span></span>

<span data-ttu-id="a69dd-104">System.IdentityModel.IdentityModelAsyncCallbackThrewException</span><span class="sxs-lookup"><span data-stu-id="a69dd-104">System.IdentityModel.IdentityModelAsyncCallbackThrewException</span></span>  
  
## <a name="description"></a><span data-ttu-id="a69dd-105">설명</span><span class="sxs-lookup"><span data-stu-id="a69dd-105">Description</span></span>  

 <span data-ttu-id="a69dd-106">비동기 콜백에 예외가 발생했습니다.</span><span class="sxs-lookup"><span data-stu-id="a69dd-106">An asynchronous callback threw an exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="a69dd-107">참고 항목</span><span class="sxs-lookup"><span data-stu-id="a69dd-107">See also</span></span>

- [<span data-ttu-id="a69dd-108">추적</span><span class="sxs-lookup"><span data-stu-id="a69dd-108">Tracing</span></span>](index.md)
- [<span data-ttu-id="a69dd-109">추적을 사용하여 애플리케이션 문제 해결</span><span class="sxs-lookup"><span data-stu-id="a69dd-109">Using Tracing to Troubleshoot Your Application</span></span>](using-tracing-to-troubleshoot-your-application.md)
- [<span data-ttu-id="a69dd-110">관리 및 진단</span><span class="sxs-lookup"><span data-stu-id="a69dd-110">Administration and Diagnostics</span></span>](../index.md)
